// Generated by CoffeeScript 1.6.1
var exec;

exec = require("child_process").exec;

task('build', 'builds the project', function(options) {
  exec("coffee --compile --bare --map --output .\\dist\\ --join app.js .\\src\\", function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
  exec("copy .\\src\\main.html .\\dist\\main.html /y");
  exec("xcopy .\\res .\\dist\\res /e /i /y");
  return exec("xcopy .\\lib .\\dist\\lib /e /i /y");
});
